#!/bin/bash

# Diagnostic script to check NopCommerce deployment status

SERVER_IP="172.236.28.69"
SERVER_USER="root"

echo "========================================="
echo "Checking NopCommerce Deployment Status"
echo "========================================="
echo ""
echo "Please SSH into the server and run these commands to diagnose:"
echo ""
echo "ssh $SERVER_USER@$SERVER_IP"
echo ""
echo "Then run:"
echo ""
echo "# 1. Check if application files were transferred:"
echo "ls -la /var/www/gamingpcrehab/"
echo ""
echo "# 2. Check application service status:"
echo "systemctl status gamingpcrehab"
echo ""
echo "# 3. Check application logs:"
echo "journalctl -u gamingpcrehab -n 50"
echo ""
echo "# 4. Check if application is listening on port:"
echo "netstat -tlnp | grep 5001"
echo ""
echo "# 5. Check Nginx error logs:"
echo "tail -n 50 /var/log/nginx/error.log"
echo ""
echo "# 6. Check Nginx configuration:"
echo "nginx -t"
echo ""
echo "# 7. Restart the application:"
echo "systemctl restart gamingpcrehab"
echo ""
echo "# 8. Check if dotnet runtime is installed:"
echo "dotnet --info"
echo ""
echo "========================================="